trigger:
  - main  # Endre om du bruker annen branch

pool:
  name: 'Default'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Set Python Version'

  - script: |
    ls -la
    displayName: 'List files'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m unittest discover tests
    displayName: 'Run tests'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'MyAzureConnection'
      appName: 'testlab-mariusapp'
      package: '$(System.DefaultWorkingDirectory)'
    displayName: 'Deploy to Azure'
