trigger:
  - main

pool:
  name: 'Default'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Set Python Version'

  - script: |
      dir
    displayName: 'List files'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      coverage run -m pytest -v
      coverage report
      coverage html
    displayName: 'Run tests and generate HTML coverage'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'htmlcov'
      artifactName: 'coverage-report'
      publishLocation: 'Container'
    displayName: 'Publish HTML Coverage Report'

  - task: Docker@2
    inputs:
      containerRegistry: 'MyDockerRegistryConnection'
      repository: 'mariusacr2.azurecr.io/testlab-mariusapp'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
    displayName: 'Build and Push Docker Image'

  - task: AzureWebAppContainer@1
    inputs:
      azureSubscription: 'MyAzureConnection'
      appName: 'testlab-mariusapp'
      imageName: 'mariusacr2.azurecr.io/testlab-mariusapp:latest'
      containerRegistry: 'MyDockerRegistryConnection'
    displayName: 'Deploy Container to Web App'
